using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Spawn : MonoBehaviour
{
    public GameObject prefab;
    public float spawnRate = 1f;
    public float minHeight = -1f;
    public float maxHeight = -1f;

    private  void OnEnable()
    {
        InvokeRepeating(nameof(Spawner), spawnRate, spawnRate);
    }

     private void OnDisable() {
        CancelInvoke(nameof(Spawner));
    } 
    private void Spawner(){
        GameObject pipes = Instantiate(prefab, transform.position, Quaternion.identity);
        pipes.transform.position += Vector3.up * Random.Range(minHeight, maxHeight);
    }
}
